import type { Division, Project, SiteSettings, Testimonial } from "./types";

// Bundled fallback content, mirrors the Supabase seed. Used when the database
// is unreachable (e.g. sandboxed builds) so the site always renders complete.

export const fallbackDivisions: Division[] = [
  {
    id: "tech",
    slug: "tech",
    sort_order: 1,
    name_ar: "Aysel Tech",
    name_en: "Aysel Tech",
    tagline_ar: "الخدمات البرمجية",
    tagline_en: "Software Services",
    description_ar:
      "حلول برمجية متكاملة تواكب أحدث التقنيات وتدعم نمو أعمالك الرقمية.",
    description_en:
      "End-to-end software solutions built with the latest technologies to power your digital growth.",
    icon: "code",
    published: true,
    services: [
      { id: "t1", division_id: "tech", sort_order: 1, name_ar: "تطوير مواقع الويب", name_en: "Web Development", published: true },
      { id: "t2", division_id: "tech", sort_order: 2, name_ar: "تطوير تطبيقات الجوال", name_en: "Mobile App Development", published: true },
      { id: "t3", division_id: "tech", sort_order: 3, name_ar: "تطوير الهويات البصرية الرقمية", name_en: "Digital Brand Development", published: true },
      { id: "t4", division_id: "tech", sort_order: 4, name_ar: "أنظمة محاسبية و ERP", name_en: "Accounting & ERP Systems", published: true },
      { id: "t5", division_id: "tech", sort_order: 5, name_ar: "حلول برمجية مخصصة", name_en: "Custom Software Solutions", published: true },
    ],
  },
  {
    id: "media",
    slug: "media",
    sort_order: 2,
    name_ar: "Aysel Media",
    name_en: "Aysel Media",
    tagline_ar: "التصميم والإبداع",
    tagline_en: "Design & Creativity",
    description_ar: "تصاميم احترافية تروي قصة علامتك التجارية وتميزها في السوق.",
    description_en:
      "Professional designs that tell your brand story and set you apart in the market.",
    icon: "palette",
    published: true,
    services: [
      { id: "m1", division_id: "media", sort_order: 1, name_ar: "تصميم UX / UI", name_en: "UX / UI Design", published: true },
      { id: "m2", division_id: "media", sort_order: 2, name_ar: "تصميم المواقع", name_en: "Web Design", published: true },
      { id: "m3", division_id: "media", sort_order: 3, name_ar: "تصميم منشورات السوشيال ميديا", name_en: "Social Media Design", published: true },
      { id: "m4", division_id: "media", sort_order: 4, name_ar: "تصميم الهويات البصرية", name_en: "Brand Identity Design", published: true },
      { id: "m5", division_id: "media", sort_order: 5, name_ar: "تصميم الشعارات", name_en: "Logo Design", published: true },
    ],
  },
  {
    id: "marketing",
    slug: "marketing",
    sort_order: 3,
    name_ar: "Aysel Marketing",
    name_en: "Aysel Marketing",
    tagline_ar: "التسويق الرقمي",
    tagline_en: "Digital Marketing",
    description_ar:
      "استراتيجيات تسويقية مدروسة توصلك إلى جمهورك المستهدف وتحقق نتائج ملموسة.",
    description_en:
      "Data-driven marketing strategies that reach your audience and deliver measurable results.",
    icon: "megaphone",
    published: true,
    services: [
      { id: "k1", division_id: "marketing", sort_order: 1, name_ar: "تحسين محركات البحث SEO", name_en: "Search Engine Optimization (SEO)", published: true },
      { id: "k2", division_id: "marketing", sort_order: 2, name_ar: "إدارة صفحات السوشيال ميديا", name_en: "Social Media Management", published: true },
      { id: "k3", division_id: "marketing", sort_order: 3, name_ar: "إدارة المتاجر الإلكترونية", name_en: "E-commerce Management", published: true },
      { id: "k4", division_id: "marketing", sort_order: 4, name_ar: "الإعلانات الممولة", name_en: "Paid Advertising", published: true },
      { id: "k5", division_id: "marketing", sort_order: 5, name_ar: "استراتيجيات المحتوى", name_en: "Content Strategy", published: true },
    ],
  },
  {
    id: "ai",
    slug: "ai",
    sort_order: 4,
    name_ar: "Aysel AI",
    name_en: "Aysel AI",
    tagline_ar: "الذكاء الاصطناعي والأتمتة",
    tagline_en: "AI & Automation",
    description_ar:
      "نسخّر قوة الذكاء الاصطناعي لأتمتة عملياتك وإنتاج محتوى مبتكر.",
    description_en:
      "We harness the power of AI to automate your operations and create innovative content.",
    icon: "brain",
    published: true,
    services: [
      { id: "a1", division_id: "ai", sort_order: 1, name_ar: "أتمتة العمليات Automation", name_en: "Process Automation", published: true },
      { id: "a2", division_id: "ai", sort_order: 2, name_ar: "تصميم ومونتاج فيديوهات AI", name_en: "AI Video Production", published: true },
      { id: "a3", division_id: "ai", sort_order: 3, name_ar: "توليد الصور بالذكاء الاصطناعي", name_en: "AI Image Generation", published: true },
      { id: "a4", division_id: "ai", sort_order: 4, name_ar: "روبوتات المحادثة الذكية", name_en: "Intelligent Chatbots", published: true },
      { id: "a5", division_id: "ai", sort_order: 5, name_ar: "حلول AI مخصصة للأعمال", name_en: "Custom AI Business Solutions", published: true },
    ],
  },
];

export const fallbackProjects: Project[] = [
  {
    id: "hawat",
    title_ar: "منصة حوات — أتمتة النظام البحري السعودي",
    title_en: "Hawat — Saudi Maritime System Automation",
    category: "ai",
    description_ar: "تصميم منصة متكاملة لأتمتة النظام البحري السعودي: لوحات تحكم، تدفقات عمل رقمية، وتجربة استخدام مبسطة لعمليات معقدة.",
    description_en: "A complete platform design automating the Saudi maritime system: dashboards, digital workflows and a simplified UX for complex operations.",
    image_url: "/projects/hawat-card.webp",
    detail_image_url: "/projects/hawat-full.jpg",
    external_link: "",
    sort_order: 1,
    featured: true,
    published: true,
  },
  {
    id: "techmind",
    title_ar: "Technology Mind — تطبيق محتوى تفاعلي بالذكاء الاصطناعي",
    title_en: "Technology Mind — AI Interactive Content App",
    category: "ai",
    description_ar: "تطبيق تفاعلي لصناعة محتوى تحفيزي بالذكاء الاصطناعي: توليد نصوص وصور ونماذج ثلاثية الأبعاد وشخصيات كرتونية.",
    description_en: "An interactive app for AI-powered motivational content: text, image and 3D model generation with cartoon characters.",
    image_url: "/projects/techmind-card.webp",
    detail_image_url: "/projects/techmind-full.webp",
    external_link: "",
    sort_order: 2,
    featured: true,
    published: true,
  },
  {
    id: "adspanel",
    title_ar: "لوحة تحكم الحملات الإعلانية المتقدمة",
    title_en: "Advanced Campaign Control Panel",
    category: "web",
    description_ar: "تصميم منصة لإدارة الحملات الممولة بلوحة تحكم ذكية: صفحات هبوط، وضع ليلي ونهاري، و40 شاشة متكاملة بنظام تصميم موحد.",
    description_en: "A funded-ads management platform with a smart dashboard: landing pages, light & dark mode, and 40 screens on one design system.",
    image_url: "/projects/adspanel-card.webp",
    detail_image_url: "/projects/adspanel-full.webp",
    external_link: "",
    sort_order: 3,
    featured: true,
    published: true,
  },
  {
    id: "yurika",
    title_ar: "يوريكا جو — تطبيق عقارات الأردن",
    title_en: "Yurika Go — Jordan Real Estate App",
    category: "apps",
    description_ar: "تطبيق عقارات متكامل (بيع، إيجار، مقارنة) بأكثر من 50 شاشة لنظامي iOS وAndroid مع بحث على الخريطة ومحادثات مباشرة.",
    description_en: "A complete real-estate app (buy, rent, compare) with 50+ screens for iOS & Android, map search and in-app chat.",
    image_url: "/projects/yurika-card.webp",
    detail_image_url: "/projects/yurika-full.webp",
    external_link: "",
    sort_order: 4,
    featured: true,
    published: true,
  },
  {
    id: "restaurants",
    title_ar: "تطبيق تجمع المطاعم",
    title_en: "Restaurants Hub App",
    category: "apps",
    description_ar: "تطبيق يجمع المطاعم في منصة واحدة: قوائم طعام، طلبات، وتتبع توصيل بتجربة استخدام سلسة وواجهات شهية.",
    description_en: "An app bringing restaurants into one platform: menus, ordering and delivery tracking with a smooth, appetizing UI.",
    image_url: "/projects/restaurants-card.webp",
    detail_image_url: "/projects/restaurants-full.webp",
    external_link: "",
    sort_order: 5,
    featured: true,
    published: true,
  },
  {
    id: "tiktok-kitchens",
    title_ar: "تيك توك مطابخ — منصة طباخين",
    title_en: "TikTok Kitchens — Cooks Platform",
    category: "apps",
    description_ar: "منصة تربط الطباخين المنزليين بالعملاء بأسلوب فيديوهات قصيرة: استعراض الأطباق، الطلب المباشر، وتقييم الطهاة.",
    description_en: "A platform connecting home cooks with customers through short videos: browse dishes, order directly and rate chefs.",
    image_url: "/projects/tiktok-kitchens-card.webp",
    detail_image_url: "/projects/tiktok-kitchens-full.webp",
    external_link: "",
    sort_order: 6,
    featured: true,
    published: true,
  },
  {
    id: "crypto-timing",
    title_ar: "تطبيق توقيت العملات الرقمية",
    title_en: "Crypto Timing App",
    category: "apps",
    description_ar: "تطبيق لمتابعة أسواق العملات الرقمية وتوقيتاتها: أسعار لحظية، تنبيهات ذكية، ورسوم بيانية تفاعلية.",
    description_en: "An app tracking crypto markets and timings: live prices, smart alerts and interactive charts.",
    image_url: "/projects/crypto-timing-card.webp",
    detail_image_url: "/projects/crypto-timing-full.webp",
    external_link: "",
    sort_order: 7,
    featured: false,
    published: true,
  },
  {
    id: "pitch-booking",
    title_ar: "تطبيق حجز الملاعب",
    title_en: "Pitch Booking App",
    category: "apps",
    description_ar: "تطبيق لحجز الملاعب الرياضية: البحث حسب الموقع، جدولة المواعيد، والدفع الإلكتروني بخطوات بسيطة.",
    description_en: "A sports pitch booking app: location search, scheduling and online payment in a few simple steps.",
    image_url: "/projects/pitch-booking-card.webp",
    detail_image_url: "/projects/pitch-booking-full.webp",
    external_link: "",
    sort_order: 8,
    featured: false,
    published: true,
  },
  {
    id: "tow-truck",
    title_ar: "تطبيق حجز سطحة",
    title_en: "Tow Truck Booking App",
    category: "apps",
    description_ar: "تطبيق لطلب سطحات نقل السيارات: تحديد الموقع، تتبع السائق لحظياً، وتسعير واضح قبل الطلب.",
    description_en: "A tow-truck booking app: pin your location, track the driver live and see clear pricing before ordering.",
    image_url: "/projects/tow-truck-card.webp",
    detail_image_url: "/projects/tow-truck-full.webp",
    external_link: "",
    sort_order: 9,
    featured: false,
    published: true,
  },
  {
    id: "cars",
    title_ar: "تطبيق سيارات",
    title_en: "Cars Marketplace App",
    category: "apps",
    description_ar: "منصة لبيع وشراء السيارات: إعلانات مفصلة، فلاتر بحث دقيقة، ومحادثة مباشرة بين البائع والمشتري.",
    description_en: "A cars marketplace: detailed listings, precise search filters and direct chat between buyer and seller.",
    image_url: "/projects/cars-card.webp",
    detail_image_url: "/projects/cars-full.webp",
    external_link: "",
    sort_order: 10,
    featured: false,
    published: true,
  },
  {
    id: "butcher",
    title_ar: "تطبيق مذبح — ذبائح وتوصيل",
    title_en: "Butcher App — Fresh Meat Delivery",
    category: "apps",
    description_ar: "تطبيق لطلب الذبائح واللحوم الطازجة مع خيارات التقطيع والتغليف والتوصيل للمنزل.",
    description_en: "An app for ordering fresh meat with cutting, packaging and home-delivery options.",
    image_url: "/projects/butcher-card.webp",
    detail_image_url: "/projects/butcher-full.webp",
    external_link: "",
    sort_order: 11,
    featured: false,
    published: true,
  },
  {
    id: "elegantie",
    title_ar: "إيلجانتي ستور — تطبيق عروض وتسوق",
    title_en: "Elegantie Store — Offers & Shopping App",
    category: "ecommerce",
    description_ar: "متجر إلكتروني للعروض والتخفيضات بأكثر من 50 شاشة: سلة مشتريات، دفع إلكتروني، وإشعارات عروض لحظية.",
    description_en: "An offers-and-deals shopping app with 50+ screens: cart, online payment and instant deal notifications.",
    image_url: "/projects/elegantie-card.webp",
    detail_image_url: "/projects/elegantie-full.webp",
    external_link: "",
    sort_order: 12,
    featured: false,
    published: true,
  },
  {
    id: "sumernr",
    title_ar: "متجر سومرنر الإلكتروني",
    title_en: "Sumernr Online Store",
    category: "ecommerce",
    description_ar: "تصميم متجر إلكتروني متكامل بهوية عصرية: تصفح منتجات، مفضلة، سلة ودفع إلكتروني آمن.",
    description_en: "A complete online store with a modern identity: product browsing, wishlist, cart and secure checkout.",
    image_url: "/projects/sumernr-card.webp",
    detail_image_url: "/projects/sumernr-full.jpg",
    external_link: "",
    sort_order: 13,
    featured: false,
    published: true,
  },
  {
    id: "tripaty",
    title_ar: "تريباتي — موقع سياحة وسفر",
    title_en: "Tripaty — Travel & Tourism Website",
    category: "web",
    description_ar: "موقع إلكتروني لشركة سياحة: باقات سفر، حجوزات، ووجهات سياحية بواجهة أنيقة سريعة التصفح.",
    description_en: "A travel agency website: packages, bookings and destinations in an elegant, fast interface.",
    image_url: "/projects/tripaty-card.webp",
    detail_image_url: "/projects/tripaty-full.webp",
    external_link: "",
    sort_order: 14,
    featured: false,
    published: true,
  },
  {
    id: "tadhaker",
    title_ar: "تذاكر — منصة حجز تذاكر",
    title_en: "Tadhaker — Ticketing Platform",
    category: "web",
    description_ar: "منصة لحجز تذاكر الفعاليات والمناسبات: استعراض الفعاليات، اختيار المقاعد، ودفع إلكتروني سريع.",
    description_en: "An event ticketing platform: browse events, pick seats and pay online in seconds.",
    image_url: "/projects/tadhaker-card.webp",
    detail_image_url: "/projects/tadhaker-full.webp",
    external_link: "",
    sort_order: 15,
    featured: false,
    published: true,
  },
  {
    id: "monasabah",
    title_ar: "مناسبة — تطبيق إدارة المناسبات",
    title_en: "Monasabah — Events Management App",
    category: "apps",
    description_ar: "تطبيق احترافي لتنظيم المناسبات: دعوات رقمية، إدارة الضيوف، وتنسيق مقدمي الخدمات في مكان واحد.",
    description_en: "A professional events app: digital invitations, guest management and vendor coordination in one place.",
    image_url: "/projects/monasabah-card.webp",
    detail_image_url: "/projects/monasabah-full.webp",
    external_link: "",
    sort_order: 16,
    featured: false,
    published: true,
  },
];

export const fallbackTestimonials: Testimonial[] = [
  {
    id: "s1",
    avatar_url: "",
    name_ar: "عبدالله القحطاني",
    name_en: "Abdullah Al-Qahtani",
    role_ar: "الرئيس التنفيذي — شركة عقارية، الرياض",
    role_en: "CEO — Real Estate Co., Riyadh",
    text_ar:
      "فريق أيسل حوّل فكرتنا إلى منصة عقارية متكاملة تعمل باحترافية عالية. الالتزام بالمواعيد والجودة فاق توقعاتنا، والدعم بعد التسليم كان ممتازاً.",
    text_en:
      "The Aysel team turned our idea into a complete real-estate platform that runs with high professionalism. Their commitment to deadlines and quality exceeded our expectations.",
    sort_order: 1,
    published: true,
  },
  {
    id: "s2",
    avatar_url: "",
    name_ar: "نورة الشمري",
    name_en: "Noura Al-Shammari",
    role_ar: "مديرة التسويق — متجر إلكتروني، جدة",
    role_en: "Marketing Manager — E-commerce, Jeddah",
    text_ar:
      "إدارة متجرنا وحملاتنا الإعلانية مع أيسل ضاعفت مبيعاتنا خلال أشهر قليلة. احترافية في التعامل ونتائج ملموسة نفخر بها. أنصح بهم بقوة.",
    text_en:
      "Managing our store and ad campaigns with Aysel doubled our sales in just a few months. Professional to work with and real, measurable results.",
    sort_order: 2,
    published: true,
  },
  {
    id: "s3",
    avatar_url: "",
    name_ar: "فهد العنزي",
    name_en: "Fahad Al-Anazi",
    role_ar: "مؤسس تطبيق — الرياض",
    role_en: "App Founder — Riyadh",
    text_ar:
      "صمموا ونفّذوا تطبيقنا بواجهات سلسة وتجربة استخدام مبهرة. تعامل راقٍ وفريق يفهم السوق السعودي جيداً. شراكة حقيقية بكل معنى الكلمة.",
    text_en:
      "They designed and built our app with smooth interfaces and an impressive user experience. A classy team that truly understands the Saudi market.",
    sort_order: 3,
    published: true,
  },
  {
    id: "s4",
    avatar_url: "",
    name_ar: "سارة الدوسري",
    name_en: "Sara Al-Dosari",
    role_ar: "مديرة منتج — شركة تقنية، الدمام",
    role_en: "Product Manager — Tech Co., Dammam",
    text_ar:
      "الهوية البصرية والمنصة اللي طوروها لنا صارت علامة فارقة في السوق. إبداع في التصميم والتزام بالجودة من أول لقاء حتى الإطلاق.",
    text_en:
      "The visual identity and platform they built became a real market differentiator for us. Creative design and quality commitment from day one to launch.",
    sort_order: 4,
    published: true,
  },
];

export const fallbackSettings: SiteSettings = {
  contact: {
    email: "info@ayselagency.com",
    phone: "",
    whatsapp: "",
    address_ar: "نخدم عملاءنا حول العالم",
    address_en: "Serving clients worldwide",
  },
  social: {
    instagram: "",
    facebook: "",
    linkedin: "",
    behance: "https://www.behance.net/mahmoudalagha",
    x: "",
    tiktok: "",
    youtube: "",
  },
  stats: { years: 5, projects: 200, clients: 80, team: 15 },
};
